/*
 * Enforces that risk_core.js reproduces fsrp.py exactly.
 *
 * The fixture is generated by src/risk/export_risk_model.py from the Python model.
 * If anyone edits the JS arithmetic, the coefficient file, or the export, and the two
 * implementations stop agreeing, this fails. Tolerance is 1e-12 -- these are the same
 * closed-form operations in both languages, so anything larger means a real divergence.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
globalThis.RISK_MODEL = JSON.parse(
  fs.readFileSync(path.join(ROOT, "src/risk/risk_model_export.json"), "utf8"));
const R = require(path.join(ROOT, "src/risk/risk_core.js"));

const fixture = JSON.parse(
  fs.readFileSync(path.join(ROOT, "tests/risk_parity_fixture.json"), "utf8"));

let pass = 0, fail = 0, worst = 0, worstCase = null;

for (const c of fixture.cases) {
  const p = {
    age: c.age, sex: c.sex, sbp: c.sbp, on_htn_meds: c.on_htn_meds,
    diabetes: c.diabetes, current_smoker: c.current_smoker,
    prevalent_cvd: c.prevalent_cvd, atrial_fib: c.atrial_fib,
    smokeless_tobacco: c.smokeless_tobacco
  };
  const got = R.risk(p, c.set);
  const diff = Math.abs(got - c.expected_risk);
  if (diff > worst) { worst = diff; worstCase = { c, got }; }
  if (diff < 1e-12) pass++;
  else {
    fail++;
    if (fail <= 5) {
      console.error(`FAIL ${c.set} ${c.sex} age=${c.age} sbp=${c.sbp} ` +
        `meds=${c.on_htn_meds} dm=${c.diabetes} smk=${c.current_smoker} ` +
        `cvd=${c.prevalent_cvd} af=${c.atrial_fib} slt=${c.smokeless_tobacco}\n` +
        `     python=${c.expected_risk}  js=${got}  diff=${diff}`);
    }
  }
}

console.log(`Python/JS parity: ${pass} matched, ${fail} diverged (of ${fixture.cases.length})`);
console.log(`Worst absolute difference: ${worst.toExponential(3)}`);

// --- behavioural checks on the JS side ---
function check(name, ok, detail) {
  if (ok) { console.log(`[PASS] ${name}${detail ? "  -- " + detail : ""}`); pass++; }
  else { console.error(`[FAIL] ${name}${detail ? "  -- " + detail : ""}`); fail++; }
}

const known = { age: 68, sex: "men", sbp: 140, on_htn_meds: false, diabetes: false,
                current_smoker: false, prevalent_cvd: false, atrial_fib: false,
                smokeless_tobacco: false };
const e1 = R.estimate(known);
check("fully-known profile yields a point estimate (no interval)",
  e1.is_certain && e1.interval_width_pct < 1e-9,
  `width ${e1.interval_width_pct.toExponential(2)}`);

const partial = Object.assign({}, known, { sbp: null, atrial_fib: null });
const e2 = R.estimate(partial);
check("unknown inputs widen the interval", e2.interval_width_pct > 0.1,
  `${e2.low_pct.toFixed(2)}% - ${e2.high_pct.toFixed(2)}%`);
check("unknowns are reported", e2.unknown_fields.length === 2);
check("value-of-information is non-negative and ranked",
  e2.value_of_information.every(r => r.variance_share >= 0) &&
  e2.value_of_information[0].variance_share >= e2.value_of_information[1].variance_share);

const e3 = R.estimate(known, { seed: 5 });
const e4 = R.estimate(known, { seed: 5 });
check("estimates are reproducible for a fixed seed", e3.point_pct === e4.point_pct);

check("under-55 is flagged as extrapolation",
  R.applicability({ age: 45, sex: "men", sbp: 120 }).status === "extrapolation");
check("in-range age is not flagged",
  R.applicability({ age: 68, sex: "men", sbp: 120 }).status === "in_range");
check("very high BP raises a separate note",
  R.applicability({ age: 68, sex: "men", sbp: 195 }).notes.length > 0);

const cf = R.counterfactuals({ age: 70, sex: "men", sbp: 165, on_htn_meds: true,
  diabetes: true, current_smoker: true, prevalent_cvd: false, atrial_fib: false,
  smokeless_tobacco: true });
check("counterfactuals are offered for a modifiable profile", cf.options.length > 0);
check("chewing tobacco is offered as a lever when present",
  cf.options.some(o => /chewing tobacco/i.test(o.change)),
  cf.options.map(o => o.change).join(" | "));
check("counterfactuals never suggest starting medication",
  !cf.options.some(o => /medication|start.*drug|take.*pill/i.test(o.change)),
  cf.options.map(o => o.change).join(" | "));
check("counterfactuals all reduce risk",
  cf.options.every(o => o.relative_reduction === null || o.relative_reduction > 0));

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
