/*
 * BrainShield — 5-year absolute stroke risk, client side.
 *
 * Mirrors src/risk/fsrp.py and src/risk/uncertainty.py exactly. Parity is enforced by
 * tests/test_risk_parity.js against a fixture of Python-computed values, so this file
 * cannot drift from the Python without the test suite failing.
 *
 * Model:  risk(t|x) = 1 - S0(t) ^ exp(LP(x) - M)
 * All constants come from RISK_MODEL (generated by src/risk/export_risk_model.py from
 * published cohort tables; see src/risk/coefficients.json for per-parameter sources).
 */
(function (root) {
  "use strict";

  var UNCERTAIN_FIELDS = ["sbp", "on_htn_meds", "diabetes", "atrial_fib",
                          "prevalent_cvd", "current_smoker", "smokeless_tobacco"];

  function getModel() {
    var M = root.RISK_MODEL;
    if (!M) throw new Error("RISK_MODEL not loaded");
    return M;
  }

  function setFor(setName, sex) {
    var M = getModel();
    var s = M.sets[setName || M.default_set];
    if (!s) throw new Error("unknown coefficient set: " + setName);
    var e = s.sexes[sex];
    if (!e) throw new Error("sex must be 'men' or 'women', got " + sex);
    return e;
  }

  /* ---- linear predictor -------------------------------------------------- */
  function linearPredictor(p, setName) {
    var e = setFor(setName, p.sex), b = e.betas;
    var lp = b.age * p.age;
    if (p.age >= 65) lp += b.age_ge65;
    if (p.current_smoker) lp += b.current_smoking;
    if (p.prevalent_cvd) lp += b.prevalent_cvd;
    if (p.atrial_fib) lp += b.atrial_fib;
    if (p.diabetes) lp += (p.age >= 65) ? b.dm_age_ge65 : b.dm_age_lt65;
    if (p.on_htn_meds) lp += b.htn_treatment + b.sbp_treated * p.sbp;
    else lp += b.sbp_untreated * p.sbp;
    return lp + adjunctLP(p);
  }

  /* Extra terms for factors absent from the source cohort model.
     Centred at ZERO, not at population prevalence: smokeless tobacco use was
     negligible in the base cohort, so non-use already is the reference level S0 was
     calibrated against. A user gets +ln(HR); a non-user gets nothing. */
  function adjunctLP(p) {
    var adj = getModel().adjunct_terms;
    var lp = 0;
    if (adj && adj.smokeless_tobacco && p.smokeless_tobacco) {
      lp += Math.log(adj.smokeless_tobacco.hazard_ratio);
    }
    return lp;
  }

  function risk(p, setName) {
    var e = setFor(setName, p.sex);
    return 1 - Math.pow(e.S0_5yr, Math.exp(linearPredictor(p, setName) - e.M));
  }

  /* ---- applicability ----------------------------------------------------- */
  function applicability(p) {
    var M = getModel(), r = M.applicability.derived_age_range;
    var notes = [], status = "in_range";
    if (p.age < r[0]) {
      status = "extrapolation";
      notes.push("Age " + Math.round(p.age) + " is below " + r[0] + ", the youngest age this "
        + "model was derived on. Read the estimate as a rough indication of direction, "
        + "not as a calibrated probability.");
    } else if (p.age > r[1]) {
      status = "extrapolation";
      notes.push("Age " + Math.round(p.age) + " is above the derivation range (max " + r[1] + ").");
    }
    if (p.sbp > 180) {
      notes.push("A systolic blood pressure above 180 mmHg needs medical attention in its "
        + "own right, separately from any 5-year estimate.");
    }
    return { status: status, notes: notes, derived_age_range: r };
  }

  /* ---- deterministic RNG so results are reproducible --------------------- */
  function mulberry32(seed) {
    return function () {
      seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
      var t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  function gauss(rand) {   // Box-Muller
    var u = 0, v = 0;
    while (u === 0) u = rand();
    while (v === 0) v = rand();
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }

  /* ---- uncertainty propagation ------------------------------------------- */
  function unknownsOf(p) {
    return UNCERTAIN_FIELDS.filter(function (f) {
      return p[f] === null || p[f] === undefined;
    });
  }

  function sampleRisks(p, n, seed, setName) {
    var e = setFor(setName, p.sex), b = e.betas, pr = e.priors;
    var rand = mulberry32(seed), out = new Float64Array(n);
    var ge65 = p.age >= 65;
    var adjT = getModel().adjunct_terms;
    var adjHR = (adjT && adjT.smokeless_tobacco) ? adjT.smokeless_tobacco.hazard_ratio : null;

    for (var i = 0; i < n; i++) {
      var treated = (p.on_htn_meds === null || p.on_htn_meds === undefined)
        ? (rand() < pr.on_htn_meds) : !!p.on_htn_meds;
      var dm = (p.diabetes === null || p.diabetes === undefined)
        ? (rand() < pr.diabetes) : !!p.diabetes;
      var smk = (p.current_smoker === null || p.current_smoker === undefined)
        ? (rand() < pr.current_smoker) : !!p.current_smoker;
      var cvd = (p.prevalent_cvd === null || p.prevalent_cvd === undefined)
        ? (rand() < pr.prevalent_cvd) : !!p.prevalent_cvd;
      var af = (p.atrial_fib === null || p.atrial_fib === undefined)
        ? (rand() < pr.atrial_fib) : !!p.atrial_fib;
      var slt = (p.smokeless_tobacco === null || p.smokeless_tobacco === undefined)
        ? (rand() < (pr.smokeless_tobacco || 0)) : !!p.smokeless_tobacco;

      var sbp;
      if (p.sbp === null || p.sbp === undefined) {
        var mean = treated ? pr.sbp_treated_mean : pr.sbp_untreated_mean;
        sbp = Math.min(240, Math.max(80, mean + pr.sbp_sd * gauss(rand)));
      } else sbp = p.sbp;

      var lp = b.age * p.age + (ge65 ? b.age_ge65 : 0);
      if (smk) lp += b.current_smoking;
      if (cvd) lp += b.prevalent_cvd;
      if (af) lp += b.atrial_fib;
      if (dm) lp += ge65 ? b.dm_age_ge65 : b.dm_age_lt65;
      if (treated) lp += b.htn_treatment + b.sbp_treated * sbp;
      else lp += b.sbp_untreated * sbp;
      if (slt && adjHR) lp += Math.log(adjHR);

      out[i] = 1 - Math.pow(e.S0_5yr, Math.exp(lp - e.M));
    }
    return out;
  }

  function pct(sorted, q) {
    var i = (sorted.length - 1) * q, lo = Math.floor(i), hi = Math.ceil(i);
    return lo === hi ? sorted[lo] : sorted[lo] + (i - lo) * (sorted[hi] - sorted[lo]);
  }
  function variance(a) {
    var m = 0, i;
    for (i = 0; i < a.length; i++) m += a[i];
    m /= a.length;
    var v = 0;
    for (i = 0; i < a.length; i++) v += (a[i] - m) * (a[i] - m);
    return v / a.length;
  }

  var LABELS = {
    sbp: "your systolic blood pressure",
    on_htn_meds: "whether you take blood-pressure medication",
    diabetes: "whether you have diabetes",
    atrial_fib: "whether you have atrial fibrillation",
    prevalent_cvd: "whether you have existing heart or vascular disease",
    current_smoker: "whether you currently smoke",
    smokeless_tobacco: "whether you chew or hold tobacco (gutkha, khaini, zarda, paan masala)"
  };
  var HOWTO = {
    sbp: "A pharmacy BP machine, a clinic, or a home cuff. Take it twice, seated, and average.",
    on_htn_meds: "Check your prescriptions for amlodipine, lisinopril, losartan, ramipril, "
               + "telmisartan, a thiazide, or similar.",
    diabetes: "A fasting glucose or HbA1c test.",
    atrial_fib: "Requires an ECG. If you have had palpitations or an irregular pulse, ask a "
              + "doctor — untreated AF is one of the most treatable stroke risks there is.",
    prevalent_cvd: "A prior heart attack, angina, bypass, stent, heart failure or peripheral "
                 + "artery disease all count.",
    current_smoker: "Any smoking in the past year counts.",
    smokeless_tobacco: "Gutkha, khaini, zarda, paan masala, mishri, or betel quid (paan) with "
                     + "tobacco \u2014 chewed or held in the mouth rather than smoked."
  };

  /* First-order Sobol index: share of output variance each unknown explains. */
  function valueOfInformation(p, n, seed, setName) {
    var e = setFor(setName, p.sex), pr = e.priors;
    var base = sampleRisks(p, n, seed, setName);
    var baseVar = variance(base);
    var sortedBase = Array.prototype.slice.call(base).sort(function (a, b) { return a - b; });
    var baseW = pct(sortedBase, 0.9) - pct(sortedBase, 0.1);

    return unknownsOf(p).map(function (field) {
      var expVar, expW;
      if (field === "sbp") {
        var rand = mulberry32(seed + 17);
        var centre = (p.on_htn_meds === null || p.on_htn_meds === undefined)
          ? pr.on_htn_meds * pr.sbp_treated_mean + (1 - pr.on_htn_meds) * pr.sbp_untreated_mean
          : (p.on_htn_meds ? pr.sbp_treated_mean : pr.sbp_untreated_mean);
        var vs = 0, ws = 0, K = 16;
        for (var k = 0; k < K; k++) {
          var c = Math.min(240, Math.max(80, centre + pr.sbp_sd * gauss(rand)));
          var q = Object.assign({}, p); q.sbp = c;
          var r = sampleRisks(q, Math.max(2000, n / 8 | 0), seed + 23, setName);
          vs += variance(r);
          var sr = Array.prototype.slice.call(r).sort(function (a, b) { return a - b; });
          ws += pct(sr, 0.9) - pct(sr, 0.1);
        }
        expVar = vs / K; expW = ws / K;
      } else {
        var pt = pr[field];
        var qt = Object.assign({}, p); qt[field] = true;
        var qf = Object.assign({}, p); qf[field] = false;
        var rt = sampleRisks(qt, n, seed + 4, setName);
        var rf = sampleRisks(qf, n, seed + 5, setName);
        expVar = pt * variance(rt) + (1 - pt) * variance(rf);
        var st = Array.prototype.slice.call(rt).sort(function (a, b) { return a - b; });
        var sf = Array.prototype.slice.call(rf).sort(function (a, b) { return a - b; });
        expW = pt * (pct(st, 0.9) - pct(st, 0.1)) + (1 - pt) * (pct(sf, 0.9) - pct(sf, 0.1));
      }
      return {
        field: field,
        label: LABELS[field],
        how_to_find_out: HOWTO[field],
        variance_share: baseVar > 0 ? Math.max(0, (baseVar - expVar) / baseVar) : 0,
        current_width_pct: 100 * baseW,
        expected_width_pct: 100 * expW
      };
    }).sort(function (a, b) { return b.variance_share - a.variance_share; });
  }

  function estimate(p, opts) {
    opts = opts || {};
    var n = opts.n || 20000, seed = opts.seed || 11, setName = opts.set;
    var unk = unknownsOf(p);
    var risks = sampleRisks(p, n, seed, setName);
    var sorted = Array.prototype.slice.call(risks).sort(function (a, b) { return a - b; });
    var out = {
      point_pct: 100 * (unk.length ? pct(sorted, 0.5) : risks[0]),
      low_pct: 100 * pct(sorted, 0.1),
      high_pct: 100 * pct(sorted, 0.9),
      is_certain: unk.length === 0,
      unknown_fields: unk,
      horizon_years: 5,
      applicability: applicability(p)
    };
    out.interval_width_pct = out.high_pct - out.low_pct;
    if (unk.length) out.value_of_information = valueOfInformation(p, Math.min(n, 12000), seed + 1, setName);
    return out;
  }

  /* ---- counterfactuals ---------------------------------------------------
   * "Start blood-pressure medication" is deliberately NOT offered. At a fixed measured
   * SBP the fitted model gives treated people lower risk than untreated people — an
   * artifact of the flatter SBP-risk slope observed in treated cohorts, not a causal
   * treatment effect. Offering it would tell users a pill beats lowering their BP.
   * The honest lever is the SBP value itself.
   * -------------------------------------------------------------------- */
  function counterfactuals(p, setName) {
    var current = risk(p, setName), out = [];
    function add(label, mod, caveat) {
      var q = Object.assign({}, p, mod), r = risk(q, setName);
      if (r < current - 1e-12) {
        out.push({
          change: label, new_risk_pct: 100 * r,
          absolute_reduction_pct_points: 100 * (current - r),
          relative_reduction: (current - r) / current, caveat: caveat || null
        });
      }
    }
    if (p.sbp > 120) {
      [140, 130, 120].forEach(function (t) {
        if (p.sbp > t) add("Lower systolic BP from " + Math.round(p.sbp) + " to " + t + " mmHg",
          { sbp: t }, "Achieved with a doctor — through treatment, salt reduction, weight "
                    + "loss and exercise. Not something this tool can prescribe.");
      });
    }
    if (p.smokeless_tobacco) {
      add("Stop chewing tobacco", { smokeless_tobacco: false },
        "Modelled as the contrast with a non-user, using a pooled hazard ratio from a "
      + "meta-analysis of chewing-tobacco users.");
    }
    if (p.current_smoker) {
      add("Stop smoking", { current_smoker: false },
        "The model treats smoking as current/not-current, so this is the contrast with a "
      + "non-smoker rather than a predicted trajectory after quitting.");
    }
    if (p.atrial_fib) {
      out.push({
        change: "Atrial fibrillation — ask about anticoagulation",
        new_risk_pct: null, absolute_reduction_pct_points: null, relative_reduction: null,
        caveat: "AF is an input to this model, so it cannot be switched off here. But "
              + "AF-related stroke is substantially preventable with appropriate "
              + "anticoagulation. Worth raising with a doctor now."
      });
    }
    out.sort(function (a, b) { return (b.relative_reduction || 0) - (a.relative_reduction || 0); });
    return { current_risk_pct: 100 * current, options: out };
  }

  var API = {
    linearPredictor: linearPredictor, risk: risk, applicability: applicability,
    estimate: estimate, valueOfInformation: valueOfInformation,
    counterfactuals: counterfactuals, unknownsOf: unknownsOf,
    UNCERTAIN_FIELDS: UNCERTAIN_FIELDS
  };
  if (typeof module !== "undefined" && module.exports) module.exports = API;
  root.BrainShieldRisk = API;
})(typeof globalThis !== "undefined" ? globalThis : this);
